### ISSUE TITLE
Feat: sidebar 섹션 추가

### ISSUE THREAD

**Issue by jeongdopark** [sniperfactory-official/sfac-lms-team-b#122]
### Todo

- [ ] 사이드바에서 Course 추가
- [ ] 사이드바에서 선택된 Course만 수정 시, 체크박스 생성
- [ ] 사이드바에서 선택된 Course의 Lecture만 리스트 보이기
