### ISSUE TITLE
Feat: 과제 상세 페이지/과제 파일 제출 기능 구현 

### ISSUE THREAD

**Issue by gonasooc** [sniperfactory-official/sfac-lms-team-b#13]
### Todo

- [x] 파일 첨부 기능 구현
- [x] react-dropzone 반영
- [x] 파일 5개 이상일 때 dropzone 숨김 처리
- [x] 개별 파일 삭제 기능 구현
- [x]  pdf, png, gif, jpg, mp4 만 업로드 제한 처리 
- [x] 사용자 패턴에 따른 토스트ui 분기처리
- [ ] 중복파일 필터
- [x] 개별 파일 용량 제한 5MB 처리
- [x] custom hook을 통한 firebase 처리
- [x] 토스트 ui 구현
