### ISSUE TITLE
Feat: 댓글의 답글 Count 기능 구현 및 파일 구조 변경

### ISSUE THREAD

**Issue by leeyulgok** [sniperfactory-official/sfac-lms-team-b#131]
### Todo

- [x] 댓글에 답글을 입력할 경우 답글의 수가 증가하는 기능 추가
- [x] 댓글에 답글을 삭제할 경우 답글의 수가 감소하는 기능 추가
- [x] Query, Mutation 함수에 맞게 파일 이동

---

## Bug report (optional)

> 버그에 대해 알려주세요

> 참고자료가 있다면 첨부해주세요.
