### ISSUE TITLE
Feat: feedback 삭제 기능 구현

### ISSUE THREAD

**Issue by Hun5LEE** [sniperfactory-official/sfac-lms-team-b#18]
### Todo

- [x] 삭제 누를시 한번더 확인, 취소 모달 띄워주기
- [x] 취소누르면 삭제모달 삭제
- [x] 확인누르면 좌측하단에 삭제가 완료되었습니다 띄우기
- [x] 스타일링
