### ISSUE TITLE
Update: 과제 등록시 userId/ readStudents 값 추가 

### ISSUE THREAD

**Issue by Yuni0221** [sniperfactory-official/sfac-lms-team-b#190]
### Todo

- [x] 과제 등록 데이터 전송시 userId / readStudents 값 추가
- [x] userId는 로그인 후 과제 등록시, useAuth에서 참조값을 가지고 옵니다
- [x] readStudents는 빈값으로 넘겨줍니다

---

**Comment by Yuni0221** [comment]
close
