### ISSUE TITLE
Feat: /classroom 페이지 디테일 작업

### ISSUE THREAD

**Issue by jeongdopark** [sniperfactory-official/sfac-lms-team-b#223]
### Todo

- [x] 메인 섹션에 강의 카드 컴포넌트, 강의 type별(링크, 비디오, 노트) 분기처리
- [x] 비공개 강의 컴포넌트 생성
- [x] 강의 보기 /lectureroom 이동
- [x] 강의 삭제 모달창
- [x] custom hook 분리 리팩토링

---
