### ISSUE TITLE
Update: 과제 등록 유효성 검사 및 코드 수정

### ISSUE THREAD

**Issue by Yuni0221** [sniperfactory-official/sfac-lms-team-b#255]
### Todo

- [x] '난이도를 선택해주세요' defaultValue로 변경하고, 선택하지 못하게 disabled 처리 
- [x] 과제의 이미지를 수정할때 이미지가 등록하기에 들어가는 오류 수정
- [x] 과제등록/ 수정시 이미지는 리셋이 안되었던 오류 수정

---
