### ISSUE TITLE
Refactor: 유저 이미지 함수 중복 수정 및 CSS 수정 및 타입 오류 수정

### ISSUE THREAD

**Issue by leeyulgok** [sniperfactory-official/sfac-lms-team-b#257]
### Todo

- [x] 유저 이미지를 렌더링 할 때 중복되는 함수 수정 및 리팩토링
- [x] 강의 커뮤니티 setModalVisibility 타입에러 수정
- [x] 강의장 네비와 강의 커뮤니티 layout 맞지 않은 부분 수정

---

### 어떤 버그 인가요?

> 버그에 대해 알려주세요

### 참고 자료(optional)

> 참고자료가 있다면 첨부해주세요.
