### ISSUE TITLE
Refactor: CommentForm 컴포넌트 리팩토링 

### ISSUE THREAD

**Issue by leeyulgok** [sniperfactory-official/sfac-lms-team-b#265]
### Todo

- [x] CommentForm 리팩토링 작업 진행
- [x] 중복해서 사용하는 함수 삭제 및 통합
- [x] CommentForm 의 명확한 기능 분리 

---

### 어떤 버그 인가요?

> 버그에 대해 알려주세요

### 참고 자료(optional)

> 참고자료가 있다면 첨부해주세요.
