### ISSUE TITLE
Feat: 비공개 강의처리 & 사이드 섹션 order 정렬

### ISSUE THREAD

**Issue by jeongdopark** [sniperfactory-official/sfac-lms-team-b#267]
### Todo

- [ ] 비공개 강의 UI
- [ ] 사이드 섹션 order 정렬 
- [ ] 사이드 섹션에서 맨 마지막 강의 삭제시 에러 이슈 해결
