### ISSUE TITLE
Refactor: 강의장 관련 함수 리팩토링

### ISSUE THREAD

**Issue by leeyulgok** [sniperfactory-official/sfac-lms-team-b#281]
### Todo

- [x] C: 댓글 등록 함수 리팩토링
- [x] R: 댓글, 강의, 이전/다음 강의 조회 함수 리팩토링
- [x] U: 댓글 수정 함수 리팩토링
- [x] D: 댓글 삭제 함수 리팩토링

---

### 어떤 버그 인가요?

> 버그에 대해 알려주세요

### 참고 자료(optional)

> 참고자료가 있다면 첨부해주세요.
