### ISSUE TITLE
Style: 클래스룸 레이아웃

### ISSUE THREAD

**Issue by jeongdopark** [sniperfactory-official/sfac-lms-team-b#3]
### Todo
- [x] /classroom 레이아웃
- [x] 사이드 섹션
- [x] 메인 컨텐츠 섹션
- [x] React-query 폴더구조 변경
- [x] React-query query-key 상수파일 생성
---

### 어떤 버그 인가요?

> 버그에 대해 알려주세요
