### ISSUE TITLE
Feat: 과제 상세 페이지/강사영역 기능 구현

### ISSUE THREAD

**Issue by gonasooc** [sniperfactory-official/sfac-lms-team-b#30]
### Todo

- [x] 학생 정보 및 제출 과제 링크 불러오기
- [x] 해당 페이지 언마운트될 때 'N' 뱃지 처리 - 강사가 페이지 빠져 나가는 순간 submittedAssignments에 isRead를 true
- [x] 과제 확인 퍼센트(ex) 63% 읽음) 구현  - 전체 학생 숫자 대비 assignment 테이블에 readStudents 체크
- [x] 과제 수정 모달 연결
- [x] 과제 삭제 기능 구현
- [x] 과제 상세 이미지 호출
