### ISSUE TITLE
Feat: 과제 상세 페이지/학생영역 기능 구현

### ISSUE THREAD

**Issue by gonasooc** [sniperfactory-official/sfac-lms-team-b#31]
### Todo

- [x] 제출 전, 제출 후 status에 따라 분기 처리
- [x] 강사만 확인 가능하게 과제 수정/삭제 버튼 ui 숨김 처리
- [x] 과제 제출 후 '확인하기' 클릭 시 과제 상세 모달 연결
- [x] 학생이 과제 읽는 순간에 readStudent에 uId 담아줘야 함
