### ISSUE TITLE
Feat: 쿠키 uid, role  정보 받아오기

### ISSUE THREAD

**Issue by jeongdopark** [sniperfactory-official/sfac-lms-team-b#321]
### Todo

- [ ] 쿠키에 저장되어 있는 uid, role 정보 페이지 이동 시
- [ ] role에 따른 분기처리 작업
- [ ] 사이드바 섹션 title 수정
