### ISSUE TITLE
Refactor: 테스트 진행 후 오류 수정

### ISSUE THREAD

**Issue by Yuni0221** [sniperfactory-official/sfac-lms-team-b#333]
### Todo

- [x] 난이도체크 유효성 검사 오류 수정
- [x] 과제 삭제시 실시간 데이터 삭제되도록 수정
- [x] nav 리스트 순서대로 등록되도록 수정

---
