### ISSUE TITLE
Update: 비디오 파일 재생시간 변환 작업 및 그 외 사소한 작업

### ISSUE THREAD

**Issue by sweeeeetpotato** [sniperfactory-official/sfac-lms-team-b#385]
### Todo
- [x] 비디오 파일의 재생시간을 강의 저장할 때 변환(예시 100초 -> 01:40 으로)하도록 수정
- [x] 강의 생성/수정을 같이하는 모달창 컴포넌트명 수정
- [x] toast 메세지창에 absolute 적용
