### ISSUE TITLE
Style: 강의장 레이아웃 구현

### ISSUE THREAD

**Issue by leeyulgok** [sniperfactory-official/sfac-lms-team-b#48]
### Todo

- [x] 강의장 전체 레이아웃 구현
- [x] 강의장 헤더 레아이웃
- [x] 강의장 강의&푸터(이전, 다음 강의) 레이아웃
- [x] 강의장 커뮤니티

---

### 어떤 버그 인가요?

> 버그에 대해 알려주세요

### 참고 자료(optional)

> 참고자료가 있다면 첨부해주세요.
