### ISSUE TITLE
Feat: /classroom data fetch & render

### ISSUE THREAD

**Issue by jeongdopark** [sniperfactory-official/sfac-lms-team-b#53]
### Todo
- [x] useQuery사용하여 lecture data fetch 
- [x] useQuery사용하여 Course data fetch
- [x] aside 섹션에 course에 해당하는 lecture list render
- [x] main 섹션에  course에 해당하는 lecture list render
- [x] aside섹션에서 course클릭 시, main 섹션에 course에 해당하는 lecture list render

---
