### ISSUE TITLE
Style: 클래스룸 페이지에서 강의 추가 모달창의 공통 컴포넌트 구현

### ISSUE THREAD

**Issue by sweeeeetpotato** [sniperfactory-official/sfac-lms-team-b#63]
### Todo
- [x] 모달창 헤더 구현
- [x] 모달창 풋터 구현
- [x] 모달창에서 강의 제목 입력하기 구현
