### ISSUE TITLE
Feat: 강의실 페이지에서의 노트만들기 모달창 스타일 및 기능 구현

### ISSUE THREAD

**Issue by sweeeeetpotato** [sniperfactory-official/sfac-lms-team-b#8]
### Todo
- [x] 노트만들기 모달창 스타일 구현
- [x] 마크다운 에디터 기능 구현
- [x] 브래드크럼에서 강의 만들기 클릭시 이전 모달창으로 이동할 수 있도록 구현
