### ISSUE TITLE
Feat: 과제 영역 모달 컴포넌트 작업

### ISSUE THREAD

**Issue by gonasooc** [sniperfactory-official/sfac-lms-team-b#86]
### Todo

- [x] props로 string값 넘겨서 title 정할 수 있게 작업
- [x] children 으로 내부 컨텐츠 개별 설정 가능하게 작업
- [x] 모달 내에 컨텐츠 스크롤 작업 ..

---
