### ISSUE TITLE
Fix: Tab 경로 및 Style 수정

### ISSUE THREAD

**Issue by jeongdopark** [sniperfactory-official/sfac-lms-team-b#97]
### Todo

- [ ] Tab 클릭 시 이동하는 경로 수정
- [ ] Tab 클릭 시 활성화 style 적용
- [ ] /classroom 푸터와 메인 섹션 겹치는 문제 해결
